[package]
name = "store_common"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.2"
swim_api = { path = "../../api/swim_api" }
serde = { version = "1.0.124", features = ["derive"] }
tempdir = "0.3.7"
thiserror = "1.0"