[package]
name = "swim_schema_derive"
version = "0.1.0"
authors = ["Swim Inc. developers info@swim.ai"]
edition = "2021"

[lib]
name = "swim_schema_derive"
proc-macro = true

[dependencies]
macro_utilities = { path = "../../macro_utilities" }
proc-macro2 = "1.0"
syn = { version = "1.0" }
quote = "1.0.3"
num-bigint = "0.3"

[dev-dependencies]
rand = "0.7"
num-bigint = { version = "0.3", features = ["rand"] }